### ISSUE TITLE
500 Error on Pledge Creation

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/klimadao#629] opened 2022-08-18 20:19 UTC
![image](https://user-images.githubusercontent.com/91024694/185487077-15873728-4127-46de-9ace-7a4f156b91d1.png)

Unclear what the underlying issue is, but it seems to be related to the Vercel Node backend since it's a generic 500 error on the `/api/pledge` endpoint

We have the user available in Discord for a troubleshooting session

**Comment by 0xAeterno** [comment] 2022-08-19 07:21
@0xAurelius can't seem to replicate this error locally or on production with a new wallet address. Happy to jump into a troubleshooting session with the user to see if we can get to the bottom of it.

@Atmosfearful would you have any thoughts on this?
Btw I'm going to prioritise this ticket (https://github.com/KlimaDAO/klimadao/issues/466). The caching strategy we're employing will prevent users from updating their pledge for ~4 minutes, if they update/create, refresh the page and update again.

**Comment by Atmosfearful** [comment] 2022-09-06 16:04
Can't reproduce, closing

**Closed by Atmosfearful** 2022-09-06 16:04 UTC
Labels: bug
