### ISSUE TITLE
[retire] Submit error using USDC to retire BCT

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1405] opened 2023-08-06 12:19 UTC
[Bug reported by Dionysus](https://discord.com/channels/841390338324824096/964698337230086174/1137659498593521735)

Getting this error when trying to retire a sizeable amount of BCT on behalf of a client: 
![image](https://github.com/KlimaDAO/klimadao/assets/103535195/21fc8651-c95f-4024-be1b-b9d494d26334)

This is after hitting 'submit'. The approval of USDC spend transaction worked fine.
I've tried Metamask on Chrome and Brave with the same error.
![image](https://github.com/KlimaDAO/klimadao/assets/103535195/35dc26a7-5860-4b8d-ad7b-ef71c05f5a1d)

I am trying to retire this project: https://www.carbonmark.com/projects/VCS-812-2009/retire/pools/bct

I just tried with Firefox and also receive the same error.
![image](https://github.com/KlimaDAO/klimadao/assets/103535195/58a93e6e-e4f3-4872-87a1-4083a159d305)

Weird that it's throwing a F2R error when I'm selecting USDC as the input payment.

Unfortunately I needed to first purchase the TCO2s for this project and then retire them manually. I assume that we missed the 1% fee on this as well as any benefit from retirement bonds.

**Comment by jabby09** [comment] 2023-08-06 12:48
@0xemc @Atmosfearful additional info

In the wallet:
![image](https://github.com/KlimaDAO/klimadao/assets/103535195/88219fdb-5f82-4a7a-88ae-6b2783cd1957)

Cost that Carbonmark displayed:
![image](https://github.com/KlimaDAO/klimadao/assets/103535195/a6de7972-c18f-4d5a-916c-7435e588d541)

Note that I moved an extra 2k USDC in to the wallet and the transaction still failed.

**Comment by jabby09** [comment] 2023-08-08 23:33
@0xemc @Atmosfearful any ideas yet on this one?

**Comment by Atmosfearful** [comment] 2023-08-10 22:35
I am not able to reproduce on Chrome Windows 11.

**Comment by 0xemc** [comment] 2023-08-10 22:46
Also unable to replicate :( 

Successful transactions:

https://polygonscan.com/tx/0x8e9dea49f2e24bf738a6939791e9115702ad3b0f77193c639c8f19404a32a05f
https://polygonscan.com/tx/0x72e237b22976ce7e3d9a3a590ed7303303cf99a37acd0c5de99147852e881201

**Comment by Atmosfearful** [comment] 2023-08-10 22:51
Evidence:
- Neither me nor Michael can reproduce this with small retirements
- Only Dionysus large $6k retirement was failing
- The "gas estimation: balance exceeded" error indicates something at the contract level, not the UI level (though im not 100% certain, I have also seen this arise if the inputs are bad)

Altogether this is a strong indicator that it's a smart contract level issue. I'm talking to @cujowolf to explore if this is maybe retirement bonds related

**Comment by jabby09** [comment] 2023-08-10 22:52
> Altogether this is a strong indicator that it's a smart contract level issue.

thanks @0xemc @Atmosfearful for the update, I'll let drew know

**Comment by Atmosfearful** [comment] 2023-08-11 00:24
More notes:
- Retirement bond should have about 9.5k BCT in it, which should be enough
![image](https://github.com/KlimaDAO/klimadao/assets/88635679/831a2e9f-fdc9-45ad-a4b2-5ab9e5a96b24)
https://polygonscan.com/address/0xa595f0d598daf144e5a7ca91e6d9a5baa09dded0
- BCT should have 60k of VCS-812-2009 in it, which should be enough
![image](https://github.com/KlimaDAO/klimadao/assets/88635679/b15e11c7-b4ec-460a-a91c-a8e5a476d643)
https://polygonscan.com/token/0xdbcb00bde2a7f1094688f59bf257374947911f5a#balances

**Comment by 0xtapi** [comment] 2023-08-11 07:36
Can confirm that there's no issue with small retirements (I retired 1 BCT on Brave from the Bull Run pool).

**Comment by Atmosfearful** [comment] 2023-08-11 21:57
Cujo observed that, looking at the encoded transaction data in the error message, *there was not enough USDC in the wallet to cover the retirement cost plus max slippage*.

In other words, the max cost with slippage is `$6,452`, which is the amount to `approve` in the first step-- even though the retirement itself costs less. His wallet only had `$6,412`.

This is an issue we've had reported once before! So this ticket can be closed in favor of https://github.com/KlimaDAO/klimadao/issues/1230

Then the last remaining question is this:
> Weird that it's throwing a F2R error when I'm selecting USDC as the input payment.
The first error screenshot was clearly not from the fiat API, but the second one is definitely from the fiat api. Which tells me we might be conflating two different bugs (or 1 bug and 1 user error). I'm tempted to say it's user error because I can't reproduce this behavior...

**Closed by Atmosfearful** 2023-08-11 21:57 UTC
Labels: bug
