### ISSUE TITLE
[profile] Profile Image URL can not be deleted

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#1098] opened 2023-04-27 13:26 UTC
## Description

When a user edited the profile and successfully added a profile image URL
=> this URL can not be removed later on

## Steps to reproduce

1. Add a profile image URL to your profile (e.g. https://i.postimg.cc/bJLxMcS8/profile-pic-original.jpg)
2. Save your profile with this URL
3. Edit again and remove this URL from your profile
4. Save Changes
5. Reload the page several times (to get the latest data from backend)
6. => Image is never removed

**Comment by Najada** [comment] 2023-04-28 13:28
@ladytrekker @jabby09 this is intended behavior.  I was asked to make this field optional for the end user to be able to update his description and name but not nessecarly his profile image.

I see two solutions:
1. Either the front end passes me down the profileImgUrl all the time if it is present so that when I don't have this attribute I consider this as a request to remove the profile pic.
2. We create another API endpoint to delete the profile image (which is a cleaner solution and its my favorite)

**Comment by ladytrekker** [comment] 2023-04-28 18:08
Thanks for the reply.

I prefer the first solution:

- When the user sends an empty string => delete the image

I may miss some technical restrictions here. 
Do you prefer the second solution because the images are hosted somewhere?

@Atmosfearful FYI ☝️

**Comment by Atmosfearful** [comment] 2023-04-28 21:52
First solution is fine for now, that seems like the quickest. When we add upload support we will need to support full deletion in the backend. No reason to worry about that yet.

**Comment by Najada** [comment] 2023-04-29 13:05
@ladytrekker @Atmosfearful proceeding with the first solution.

**Comment by Najada** [comment] 2023-05-04 14:44
@ladytrekker return null when profileImgUrl is not present works for us? If yes I can deploy the change on production and staging.

'{
    "handle": "pixel",
    "username": "pixel",
    "description": "Testing profile for pixel",
    "profileImgUrl": null,
    "wallet": "0x39497d2458f92d099cf477cb05b2cf3ca472dee0",
    "listings": [],
    "activities": [],
 .........
}'

**Comment by Najada** [comment] 2023-05-05 13:39
@ladytrekker can i deploy this update?

**Comment by ladytrekker** [comment] 2023-05-09 12:50
@Najada 

Ok, I opened a PR which sets the Profile IMG URL to `null | string`
https://github.com/KlimaDAO/klimadao/pull/1130

We can wait for that first.

**Comment by jabby09** [comment] 2023-08-01 20:29
@psparacino another one that ladytrekker and najada were working on that ended up being blocked.
You'll need to investigate to determine what is remaining.

**Comment by psparacino** [comment] 2023-08-03 21:04
@jabby09 this no longer appears to be an immediate issue.  After updating the profile img there is a delay between the changes permanently showing on both modal and page, but the image can be modified/deleted and appears to have been addressed in #1130.

The performance could be a little more smooth though; looking into if it's a quick fix. If yes, I'll make and put up a PR. If more involved I'll shelve this for the moment and continue on higher priority issues

**Comment by jabby09** [comment] 2023-09-11 19:43
> The performance could be a little more smooth though; looking into if it's a quick fix. If yes, I'll make and put up a PR. If more involved I'll shelve this for the moment and continue on higher priority issues

@psparacino confirmed this is working

the UX is very janky but no one is asking for this so we can make it a low priority and / or fix it when we look at the profile page in carbonmark v2

**Closed by jabby09** 2023-09-11 19:43 UTC
Labels: bug
