### ISSUE TITLE
[App] Completely messed up style on Microsoft Edge

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#434] opened 2022-05-19 23:14 UTC
Also, the entirety of the middle and right panes aren't loading at all.

![image](https://user-images.githubusercontent.com/99001851/169419064-e6906610-9b5e-493e-aed1-3e04d1b5e047.png)

**Comment by goatsOnDrugs** [comment] 2022-05-25 16:21
I was unable to reproduce this on windows + edge. @ShimonD-KlimaDAO are you still seeing this?

**Comment by jabby09** [comment] 2023-04-21 19:37
Almost a year old, have not seen any recent user reports about this. Closing.

**Closed by jabby09** 2023-04-21 19:37 UTC
