### ISSUE TITLE
[tech] Style discrepancy on Portfolio and Pool retirement flows

### ISSUE THREAD

**Issue by psparacino** [KlimaDAO/klimadao#1366] opened 2023-07-24 16:50 UTC
Currently the retirement flows from Portfolio and the Pool have some design divergence in the modals. 

All the modals have design dissimilarities, but a sample below on the modal after a successful transaction:

| Pool Notification  |
|--------|
|<img width="836" alt="pool not indexed" src="https://github.com/KlimaDAO/klimadao/assets/72105234/a41e9ec0-32e1-4055-9740-1c7565d0dd4d">|

| Portfolio Notification  |
|--------|
|<img width="688" alt="portfolio not indexed" src="https://github.com/KlimaDAO/klimadao/assets/72105234/bfef47fa-6ae7-4e42-bdcf-741426891ec1">|

There is also some duplicated logic under the hood, but the design changes would most likely be a lighter light and higher value add than refactoring the duplicated logic at this stage.

**Comment by Atmosfearful** [comment] 2024-01-03 00:02
This is a duplicate of #1215

**Closed by Atmosfearful** 2024-01-03 00:02 UTC
