### ISSUE TITLE
[App] Cost is not calculated for selective retirements

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#718] opened 2022-09-23 19:59 UTC
1. When I try executing a selective retirement, the cost seems to be stuck and is not calculated.

![image](https://user-images.githubusercontent.com/99001851/192047214-c8eebe11-b1e1-4238-a916-eef2ac67f09a.png)

**Comment by jabby09** [comment] 2022-10-16 11:58
@Atmosfearful this is labeled as a high priority bug, is this in your queue?

**Comment by Atmosfearful** [comment] 2022-10-25 00:33
I am not able to reproduce, I can get a quote for that token. But I believe this is related to a different issue where the loading spinner appears when you are not connected and does not disappear even after you connect. But that will be resolved with the new offset tool designs which should show a "not connected" placeholder for everything.

**Closed** 2022-10-25 00:33 UTC
Labels: bug, HIGH PRIORITY
